import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ModeToggle } from "../components/mode-toggle";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <div className="min-h-dvh flex flex-col">
            <header className="border-b">
              <div className="container mx-auto p-4 flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <Link href="/" className="font-semibold">Practical Genie</Link>
                  <nav className="flex gap-4">
                    <Link href="/" className="text-sm hover:underline">Practical Generator</Link>
                    <Link href="/experiment-ideas" className="text-sm hover:underline">Experiment Ideas</Link>
                  </nav>
                </div>
                <ModeToggle />
              </div>
            </header>
            <div className="flex-1">{children}</div>
          </div>
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
